spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/adivinalapalabra
    username: root
    password: mysql
  jpa:
    hibernate:
     ddlAuto: update
jwt:
  secret: "T4k3_Up23"
  expiration: 900000